import '@/styles/globals.css'
import "@/styles/theme.css"
import styles from "@/styles/Home.module.css"
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

export default function App({ Component, pageProps }) {
  return <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <header className={styles.containerHeader}>
      <div className={styles.containerLogoTitulo}>
        <Link href={"/"}>
          <Image
            src={"/logoIF.png"}
            alt={'Logo do IFRO'}
            width={75}
            height={75}
          />
        </Link>
        <div className={styles.containerTituloLink}>
          <h1>Plataforma de Eventos</h1>
          <Link className={styles.linkGerenciar} href="/gerenciar">Gerenciar eventos</Link>
        </div>
      </div>
    </header>

    <main className={styles.main}>
      <Component {...pageProps} />
    </main>

    <footer className={styles.containerRodape}>
      <p>Mateus de Moraes Silva</p>
    </footer>
  </>
}
